"""init schema

Revision ID: 02c04997cfcc
Revises: 
Create Date: 2026-02-11 15:17:10.202814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c04997cfcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_type_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('normalized_type', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('headers_json', sa.Text(), nullable=True),
    sa.Column('field_map_json', sa.Text(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('fee_type_raw', sa.String(length=255), nullable=False),
    sa.Column('amount_raw', sa.String(length=50), nullable=False),
    sa.Column('order_ref', sa.String(length=128), nullable=True),
    sa.Column('tracking_ref', sa.String(length=128), nullable=True),
    sa.Column('raw_row_json', sa.Text(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('fee_type_norm', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_table('invoice_uploads')
    op.drop_table('fee_type_maps')
    # ### end Alembic commands ###
